### ISSUE TITLE
Visiting /Script throws an error

### ISSUE THREAD

**Issue by HansenRene** [ironmansoftware/universal-automation#1]
#### Describe the Issue

Clicking a script in the gui redirects to /script/1 (for script ID 1), this throws an error:

An error occurred on this page
Exception calling "Invoke" with "0" argument(s): "Exception calling "Invoke" with "0" argument(s): "Exception calling "Invoke" with "0" argument(s): "A parameter cannot be found that matches parameter name 'Top'."""

#### Script Sample

Just the beta getting started with debug enabled

#### Version Information

- **Host Operating System**: Server 2019
- **Host PowerShell Version**: 5.1
- **Universal Automation Version**: 1.0.0
- **Universal Dashboard Version**: 2.7.0
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.) Windows Powershell

**Comment by adamdriscoll** [comment]
Woops. 

![image](https://user-images.githubusercontent.com/1256531/70176137-28488180-1695-11ea-89c5-60756f8685c8.png)

**Comment by HansenRene** [comment]
big oof!

**Comment by adamdriscoll** [comment]
Fixed. Will be in tonight's build. You can work around this by changing line 79 of script.ps1 in UniversalAutomation.Dashboard\pages to:

```
$ScriptHistory = Get-UAScriptHistory -Script $Script | Sort-Object -Property 'Timestamp' -Descending | Select-Object -First 1
```
