### ISSUE TITLE
Script Description Issues

### ISSUE THREAD

**Issue by leeberg** [ironmansoftware/universal-automation#10]
#### Describe the Issue

The seems to be some issues with Description

1. Creating a Script with a Description does not populate the Description
2. Set-UAScript -Description does not populate the description

#### To Reproduce

1. ``$Script = New-UAScript -Name "DescriptionTest1" -Description "Hello World" -ScriptBlock {$Derp}``
2. $Script | Set-UAScript -Description "Hello Test99"

#### Expected behavior

* Description should be applied to the Script on Create and Update
* Get commands should be able to show the description

**Comment by adamdriscoll** [comment]
This is more than just the description. Seems like the Set-UAScript cmdlet is messed up. It sets the properties into git but isn't syncing correctly to the database. Also, it seems like properties are stomping on each other. e.g. if I set description it clears manualtime etc.
