### ISSUE TITLE
Feedback input dialog box

### ISSUE THREAD

**Issue by gpduck** [ironmansoftware/universal-automation#102]
It'd be nice if pushing enter in the feedback input box would submit the feedback.  (Specifically I was using Desktop, but I'm guessing it applies to both)

**Comment by leeberg** [comment]
I like it - would make it a bit smoother to run scripts. In desktop you can "TAB" to the Run button and hit enter but just hitting enter would be nice as well

**Comment by adamdriscoll** [comment]
You can now press enter to submit feedback.
