### ISSUE TITLE
Unable to load the UniversalAutomation module

### ISSUE THREAD

**Issue by claudiospizzi** [ironmansoftware/universal-automation#109]
#### Describe the Issue

Importing the UniversalAutomation module fails:

```
Import-Module : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral,
PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
At C:\Program Files\WindowsPowerShell\Modules\UniversalAutomation\1.0.1\UniversalAutomation.psm1:1 char:1
+ Import-Module "$PSScriptRoot\UniversalAutomation.Cmdlets.dll"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

Unable to find type [UniversalAutomation.AssemblyResolver].
At C:\Program Files\WindowsPowerShell\Modules\UniversalAutomation\1.0.1\UniversalAutomation.psm1:2 char:1
+ [UniversalAutomation.AssemblyResolver]::Bind()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (UniversalAutomation.AssemblyResolver:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

#### To Reproduce

1. Windows Server 2016
2. Install UniversalAutomation Module (v1.0.1)
3. Import-Module UniversalAutomation

#### Expected behavior

The module should load without any errors

#### Screenshots

![image](https://user-images.githubusercontent.com/1934246/75493198-a6c56e80-59b9-11ea-82c3-b0e57c9f1b58.png)

#### Version Information

- **Host Operating System**: Windows Server 2016
- **Host PowerShell Version**: 5.1.14393.3383
- **Universal Automation Version**: 1.0.1
- **Universal Dashboard Version**: 2.9.0
- **UD Hosting Method**: Tryied in Powershell, IIS -> same error

**Comment by adamdriscoll** [comment]
@claudiospizzi Do you have .NET 4.7.2 or later installed on this machine?

**Comment by claudiospizzi** [comment]
No I'm on .NET Framework 4.6.2. Is v4.7.2 required? Have I missed that in the documentation. I've followed this one to set it up in IIS:
https://docs.universalautomation.io/hosting/iis

**Comment by claudiospizzi** [comment]
Oh yeah I missed it in the requirements:
https://docs.universalautomation.io/systemrequirements

I will try it with .NET 4.7.2

**Comment by claudiospizzi** [comment]
It's working with .NET 4.7.2. Maybe you can add the same .NET 4.7.2 check and error message like you have in UniversalDashbaord to UniversalAutomation?

**Comment by adamdriscoll** [comment]
Good point. I've open this issue: https://github.com/ironmansoftware/universal-automation/issues/110
