### ISSUE TITLE
White overlay when comparing scripts?

### ISSUE THREAD

**Issue by HansenRene** [ironmansoftware/universal-automation#11]
#### Describe the Issue

Comparing 2 commits Shows a modal that is just White with a little close icon - Clicking the close icon then shows the 2 scripts

#### To Reproduce

Compare 2 scripts

#### Screenshots

![image](https://user-images.githubusercontent.com/20628942/70221212-402d0d80-1748-11ea-8141-b2c8ced4a999.png)

#### Script Sample

Attempt to attach sample code that will allow others to reproduce the issue. **NOTE**: Generally speaking this is the **MOST EFFECTIVE** way to have your issue resolved.

#### Version Information

- **Host Operating System**: 2019
- **Host PowerShell Version**: 5.1
- **Universal Automation Version**: latest
- **Universal Dashboard Version**: 2.7
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.) winposh

**Comment by HansenRene** [comment]
Maybe this is of help
![image](https://user-images.githubusercontent.com/20628942/70434857-a508a080-1a85-11ea-8fc5-07139fb74163.png)

**Comment by adamdriscoll** [comment]
We don't have this functionality any more so we don't need to fix it. That said, we might add it back in a later release.
