### ISSUE TITLE
Wait-UAJob hangs indefinitely

### ISSUE THREAD

**Issue by romphreak** [ironmansoftware/universal-automation#116]
#### Describe the Issue

When using the Wait-UAJob cmdlet (either via pipeline or by itself), the powershell session hangs indefinitely and cannot be cancelled.

#### To Reproduce

Steps to reproduce the behavior: (Example)

1. Add a script to UA
2. Create job by invoking UA script
3. Either pipe the invoke to Wait-UAJob, or call Wait-UAJob by itself

#### Expected behavior

The command to complete and the powershell session to be usable again.

#### Screenshots

![image](https://user-images.githubusercontent.com/57773566/75890830-e5658980-5dfc-11ea-849c-9b472d7ce268.png)

![image](https://user-images.githubusercontent.com/57773566/75890908-029a5800-5dfd-11ea-9d32-65235125aa41.png)

#### Script Sample

$script = New-UAScript -Name FOO -ScriptBlock {Get-Process}
Invoke-UAScript $script | Wait-UAJob

-or-

$script = New-UAScript -Name FOO -ScriptBlock {Get-Process}
$job = Invoke-UAScript $script
Wait-UAJob -JobId $job.Id

#### Version Information

- **Host Operating System**: Windows 10 1903
- **Host PowerShell Version**: 5.1.18362.145
- **Universal Automation Version**: 1.0.1
- **Universal Dashboard Version**: 1.0.1
- **UD Hosting Method**: Powershell

**Comment by adamdriscoll** [comment]
Wait-UAJob was throwing an exception internally which was causing it to wait forever. This has been resolved.
