### ISSUE TITLE
Scheduled jobs stuck in Queued status

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-automation#118]
#### Describe the Issue

I've created schedule jobs to run hourly. And every hour, a new job appears as 'Queued' in the Jobs tab. Start date is showing as Jan 1, 0001 12:00 AM, and there is not output on the job.

#### Expected behavior

I'd expect the job to start and show some output.

#### Screenshots

![image](https://user-images.githubusercontent.com/9411143/75918288-4fd3f500-5e10-11ea-8472-732bc28292c8.png)

**Comment by adamdriscoll** [comment]
Ran into this as well. It's a problem with the serilog console sink. I'm disabling this for now in UA. 

https://github.com/serilog/serilog-sinks-console/issues/84
