### ISSUE TITLE
Per-Script Concurrent Job Limits

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-automation#120]
You can currently set the per-server concurrent job limit but we should also provide configuration on a per-script basis. This would allow us to allow the server to run unabated but limit an individual script.

**Comment by dcherry88** [comment]
Is there any progress on this enhancement for Automation scripts?

**Comment by adamdriscoll** [comment]
There hasn't but I'll bump it onto our 1.5 backlog

**Comment by adamdriscoll** [comment]
This was released in 1.5: https://docs.ironmansoftware.com/automation/scripts#add-a-new-script

It's not part of the UI at the moment but you can set it within the scripts.ps1 file.
