### ISSUE TITLE
View Jobs for a particular 'Script'

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-automation#129]
When looking at a script, it would be nice see 'this scripts job history'.. and not 'all jobs'.

**Comment by leeberg** [comment]
Agree! 

Jobs should be able to be filtered by Script. 

Having a "Quick View" / Shortcut / Modal / SOMETHING to see Script jobs when working on a particular script would be very useful as well.

Thanks for the feedback we'll prioritize this one

**Comment by mkellerman** [comment]
This ties in with the suggestion with #133 ..

**Comment by adamdriscoll** [comment]
This was released in 1.1.1.
