### ISSUE TITLE
Log File C:\Users\adamr\Desktop\log.txt

### ISSUE THREAD

**Issue by claudiospizzi** [ironmansoftware/universal-automation#137]
#### Describe the Issue

In a procmon.exe trace I can see, that the Universal Automation tries to write into the following file: C:\Users\adamr\Desktop\log.txt -> Do you have a hard coded log file anywhere. Because we have no users named adamr. In general, it would be great to define a log file location for UA and UD.

#### Version Information

- **Host Operating System**: WS2019
- **Host PowerShell Version**: 5.1
- **Universal Automation Version**: 1.0.1
- **Universal Dashboard Version**: 2.9.0
- **UD Hosting Method**: IIS

**Comment by claudiospizzi** [comment]
Oh by the way, that's the content of the log file:

```
2020-03-11 23:47:49.802 +01:00 [WRN] Using an in-memory repository. Keys will not be persisted to storage.
2020-03-11 23:47:49.817 +01:00 [WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
2020-03-11 23:47:49.849 +01:00 [WRN] No XML encryptor configured. Key "<<SOME GUID>>" may be persisted to storage in unencrypted form.
2020-03-11 23:48:05.271 +01:00 [DBG] Starting sync...
2020-03-11 23:48:05.286 +01:00 [DBG] Git has remote. Starting pull
2020-03-11 23:48:05.443 +01:00 [DBG] Git has remote. Starting push
2020-03-11 23:48:05.818 +01:00 [DBG] No changes.
```

**Comment by adamdriscoll** [comment]
@claudiospizzi - Nice catch. Yep. There is a hard coded path in there. I'll get that fixed and make sure you can configure it.

**Comment by adamdriscoll** [comment]
This has been resolved. The default logging path is now: C:\ProgramData\UniversalAutomation\logs

You'll be able to set the logging path to your own location using the UASettings cmdlets. 

```
$Settings = Get-UASettings
$Settings.LoggingFilePath = "C:\myLogs\logs.txt" 
$Settings.LogLevel = "verbose"
Set-UASettings -Settings $Settings
```

**Comment by claudiospizzi** [comment]
Just one question. I'm using an IIS hosted UA, there I start it with `Start-UAServer -InProcess`. I think this command will never stop until I close the AppPool. Can I somehow set the log level and path? Maybe as parameter on `Start-UAServer` or alternative by creating a settings object an passing it to the start?

```powershell
$setting = New-UASetting
Start-UAServer -Setting $setting -InProcess
```

**Comment by adamdriscoll** [comment]
Sure. That's a good point. I'll add a\some parameter(s) to Start-UAServer so we can diagnose issues at startup.

**Comment by adamdriscoll** [comment]
Also note that the logging settings are stored in the UA git repo in .ua/settings.ps1
