### ISSUE TITLE
Failed to load Universal Automation. We tried to connect to port 10000 but failed.

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-automation#138]
#### Describe the Issue

Installed UA version 1.10 on a new workstation, and received error.

#### Expected behavior

No error.. ;)

#### Screenshots

<img width="988" alt="image" src="https://user-images.githubusercontent.com/9411143/76472081-c42f0b00-63b1-11ea-8f30-dae1390bb660.png">

#### Version Information

- **Host Operating System**: Windows Server 2016
- **Universal Automation Version**: 1.10

**Comment by adamdriscoll** [comment]
@mkellerman Did restarting UA help in this environment? I've extended to time we attempt to connect to 60 seconds. It seems like for whatever reason it takes a while for UA to startup.

**Comment by mkellerman** [comment]
No. Restarted UA, and even rebooting, did not resolve the issue.

I did uninstall 1.10, and proceeded to install 1.00... and now UA won’t even load. No icon in tray, no GUI.

**Comment by adamdriscoll** [comment]
I think it does by default but does this machine have .NET v4.7.2 installed?

**Comment by adamdriscoll** [comment]
whoops

**Comment by mkellerman** [comment]
Version installed: v4.0.30319

Seems like the bug is that the installer isn't checking for prerequisites.. :P 

I'll install 4.7.2 and confirm that all is good in the world.

**Comment by mkellerman** [comment]
I installed using chocolate:
````
choco install dotnet4.7.2 -y
````

And problem persists. I tried uninstalling, and reinstalling, now that 4.7.2 was installed, and same problem.

**Comment by mkellerman** [comment]
Travelled to C:\Users\<user>\AppData\Local
Deleted the 2 UA folders, and will re-install.

**Comment by mkellerman** [comment]
Nope, that didn't work. Let me know what to try next.

**Comment by adamdriscoll** [comment]
@mkellerman Can you please try this build? https://send.firefox.com/download/d776e4d96b53f87b/#F-_OQOTUEkHKAJT1m0QuYw

Primarily, it turns on logging by default to C:\ProgramData\UniversalAutomation\logs 

Hopefully, we can catch something interesting in there.

**Comment by mkellerman** [comment]
I uninstalled and deleted the UA folders in AppData\Local, and that build worked. It opened up from the first launch! 

What does it all mean?

**Comment by adamdriscoll** [comment]
Not sure. I did extend the amount of time the UA UI will wait for the backend to start-up and add the logging but pretty much all the other changes were mostly cosmetic. I'm going to close this for now and we will continue to test and reopen with any additional information. We have logging enabled by default now so if it does happen hopefully we will see it there.
