### ISSUE TITLE
Display Complex Objects in Pipeline Output Tab

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-automation#14]
#### Is your Enhancement request related to a problem? Please describe

Complex objects (like PSObject) don't display well in the pipeline output tab. I'd love it if it was a property grid or tree view like we have in VS Code so we can display the nested properties and objects of a complex object dropped on the pipeline. 

#### Describe the solution you'd like

Property grid for complex objects.

#### Describe how this would improve your Universal Automation Quality of Life

Would be much easier to see what the objects contain.

#### Describe alternatives you've considered

Print the objects in a way thats visit to the end user but i dont think that will be as helpful.

**Comment by adamdriscoll** [comment]
Potential control: http://codecombat.github.io/treema/

**Comment by adamdriscoll** [comment]
Also: https://github.com/IngloriousCoderz/react-property-grid

**Comment by leeberg** [comment]
Partially Implemented via Grids in Public Beta Release Version!

**Comment by adamdriscoll** [comment]
This is done for v1.1.
