### ISSUE TITLE
Pipeline output tab has blank rows

### ISSUE THREAD

**Issue by leeberg** [ironmansoftware/universal-automation#140]
#### Describe the Issue

The Pipeline output seems to populate the correct number of rows / pages when outputting a variety of objects - however the content of the row is blank!

#### To Reproduce
See Script - Output Service to Pipeline (have not attempted a wide variety of types yet)

#### Screenshots

**UAD/UA UI**
![image](https://user-images.githubusercontent.com/274883/76488214-c9607a00-63f2-11ea-86ec-5f80c6c331dd.png)

**Note**, I do have the correct details in the Database
![image](https://user-images.githubusercontent.com/274883/76488743-46d8ba00-63f4-11ea-8e1f-8fd54065a7c6.png)

#### Script Sample

```powershell

$Services = Get-Service
$Services | ForEach-Object {
     Write-Output $_
}
```
#### Version Information

* UADesktop and UA
* WIndows 10 / Server 2019
* 5.1 and 7
* 1.1 and Latest Dev

**Comment by adamdriscoll** [comment]
Looks like PS 7 XML is slightly different than PS 5.1. Looking into it.

**Comment by adamdriscoll** [comment]
Even more strange...the CliXml returned within UA is different than when I run on the command line.
