### ISSUE TITLE
Slack / Discord Channel during Beta testing

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-automation#142]
#### Is your Enhancement request related to a problem? Please describe

Would be nice to have more open conversations than bug/enhancement tickets. 
Having a Slack/Discord channel would allow us to interact with the Dev's, and answer/suggest ideas directly. Once chewed a bit, we could then create a Issue in GitHub?

**Comment by adamdriscoll** [comment]
I'm going to suggest the Forums as a place for this type of discussion: https://forums.universaldashboard.io/c/universal-automation/14 

I'd rather not do real-time discussions on Slack\Discord as it's far too distracting. I'm happy to have a call if you'd like something more real-time. We should involve @leeberg if we schedule that.
