### ISSUE TITLE
Pipeline Output - Opening Child Item opens same child item type for all objects on the pipeline output

### ISSUE THREAD

**Issue by leeberg** [ironmansoftware/universal-automation#145]
#### Describe the Issue
When multiple parent objects in the Pipeline output share the SAME sub child types, opening one child item will open all other items of the same type.

#### Script Sample

```powershell
$Services = Get-Service
$Services | ForEach-Object{
    Write-Output $_
}
```

1. Run Script
2. Open the Pipeline output
3. Expand a parent item (service)
4. Expand child item (DependentSerivces)
5. Notices this expands for ALL objects on the pipeline
6. Output is also null - Is this a bug ?

#### Screenshots

![pipelinebug](https://user-images.githubusercontent.com/274883/76691076-d0ff6900-6614-11ea-9f1a-7e3b9a3bc20e.gif)

**Comment by adamdriscoll** [comment]
Resolved. We need to make sure we have a key property set on our objects so the table knows they are unique. The dependent services are just empty in your example. If you expand some of the ServicesDependOn properties you'll see they have items.
