### ISSUE TITLE
PowerShell Version Table Issues

### ISSUE THREAD

**Issue by leeberg** [ironmansoftware/universal-automation#146]
#### Describe the Issue

PowerShell version table kind of  stinks:

1. When added a new object you will have to REFRESH the page in order to edit it
2. When added a new object you will have to REFRESH the page in order to delete it

#### Suggestion

* Migrate PowerShell Version control to a "more standard" control.
* Create/Edit could be handled in a Modal similar to Script and Variable.
* Any change would ideally be semi-ANTd v4 compatible :)

#### To Reproduce

Steps to reproduce the behavior: (Example)

1. Create Version
2. Edit Version
3. REFRESH
4. Notice changes are gone :)

1. Create Version
2. Delete Version
3. Notice nothing happens
3. REFRESH
4. Notice it's still there :(

**Comment by adamdriscoll** [comment]
Version table now refreshes when you do anything. It also has a modal that pops up when you add or edit.
