### ISSUE TITLE
Job execution broken, when PowerShell 6 is installed as global DotNet Tool

### ISSUE THREAD

**Issue by dewdeded** [ironmansoftware/universal-automation#18]
UA starts and runs (daemon and web frontend) but every job execution fails, beause UA selects "pwsh.exe" in the users .dotnet\tools-directory as powershell binary/instance.

Tested Windows 10 and Windows Server 2019

Can the shell UA uses be configured?

**Comment by adamdriscoll** [comment]
Tonight's build will include New-UAPowerShellVersion to allow you to register a new version\path to pwsh.exe
