### ISSUE TITLE
Script removal (Remove-UAScript) from CLI/scripts and GUI doesnt work:

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-automation#27]
#### Describe the Issue

Script removal (Remove-UAScript) from CLI/scripts and GUI doesnt work:

#### To Reproduce

Tried CLI syntax e.g.: Remove-UAScript -Script (Get-UAScript -id 1) -AppToken $token

Call failed with status code 500 (Internal Server Error): DELETE http://example:10000/api/v1/Script/1
An unhandled exception was thrown by the application. LibGit2Sharp.NotFoundException: could not find ‘C:/Users/x/AppData/Local/UniversalAutomation/Repository/TEst.ps1’ to stat: Das System kann die angegebene Datei nicht finden.)

#### Expected behavior

Script is removed

#### Script Sample

Attempt to attach sample code that will allow others to reproduce the issue. **NOTE**: Generally speaking this is the **MOST EFFECTIVE** way to have your issue resolved.

#### Version Information

- **Host Operating System**:
- **Host PowerShell Version**:
- **Universal Automation Version**:
- **Universal Dashboard Version**:
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)

**Comment by leeberg** [comment]
Note!  I have found that if you "keep trying" to delete - it does work eventually.

You can literally go through CMDlets / GUI and it will fail but keep trying and it'll work.

**Comment by adamdriscoll** [comment]
Fixed
