### ISSUE TITLE
No output captured

### ISSUE THREAD

**Issue by HansenRene** [ironmansoftware/universal-automation#3]
#### Describe the Issue

a bit embarrased about this one.
My first script is simply this:

```
#Enter Script Here!
write-output "Cool Beans 2: electric boogaloo"
```

But when looking at the output of the job i see just a empty codeeditor.

#### Expected behavior

Cool Beans 2: electric boogaloo

#### Screenshots

![image](https://user-images.githubusercontent.com/20628942/70176495-dfb2b780-16d8-11ea-80c3-627fa9f75049.png)

- **Host Operating System**: Server2019
- **Host PowerShell Version**: 5.1
- **Universal Automation Version**: 1
- **Universal Dashboard Version**:2.7
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.) posh

**Comment by adamdriscoll** [comment]
Write-Output ends up on the pipeline and the output from this would be shown on the Pipeline Output tab (if it wasn't broken at the moment). 

I think it makes sense to also show it on the output tab. I'll make sure it ends up there as well.

**Comment by adamdriscoll** [comment]
Tonight's build will resolve this.
