### ISSUE TITLE
[UI] Timestamps are using american format (12h)

### ISSUE THREAD

**Issue by HansenRene** [ironmansoftware/universal-automation#39]
#### Describe the Issue

Any timestamps in the Dashboard (for example in the 'past jobs' tab) show AM/PM format.
The format should either match Host format, or, if not possible, use the ISO international format (https://en.wikipedia.org/wiki/ISO_8601)

**Comment by adamdriscoll** [comment]
'Merica

**Comment by adamdriscoll** [comment]
@leeberg  We can use UDMoment to support this:https://marketplace.universaldashboard.io/Dashboard/UniversalDashboard.Moment

We probably need to update it to take into account different locales.

**Comment by HansenRene** [comment]
If its a big task, maybe wait for the beta to go public, and make a poll on the forums about if time should match the host, or simply use the ISO standard - I reckon the latter would be much easier to implement?

**Comment by leeberg** [comment]
Meh! Probably easier to do it now! - We are **not** just focusing on America here so it's certainly worth doing. I think Ironman probably has more NON-US users anyways so let's please the majority :)

**Comment by adamdriscoll** [comment]
We are now using moment.js localized formats. Should no longer be in correct-datetime format on incorrect datetime-format machines. :P
