### ISSUE TITLE
Distinguish "meta" scripts in the file name

### ISSUE THREAD

**Issue by Windos** [ironmansoftware/universal-automation#44]
#### Is your Enhancement request related to a problem? Please describe

More often than I care to admit, I find myself confusing my UA scripts themselves and the "meta" versions of them under .UA as they have identical file names.

#### Describe the solution you'd like

Give the meta scripts a distinguishing string in their filename, similar to including "Test" with pester scripts.

e.g. for a script called `Get-Metrics.ps1`, the meta script could be `Get-Metrics.UA.ps1` or `Get-Metrics.Meta.ps1`

#### Describe how this would improve your Universal Automation Quality of Life

I could continue being an idiot that looks only at file names and not full paths, without causing myself issues.

**Comment by adamdriscoll** [comment]
I like that idea! This will be a breaking change unless you manually rename your scripts.

**Comment by Windos** [comment]
If a breaking change is on the cards, it's probably better sooner than later (esp when most of the testers can be warned via Slack)

**Comment by adamdriscoll** [comment]
I agree. I'll get this in today.

**Comment by adamdriscoll** [comment]
Done
