### ISSUE TITLE
Job Continuations

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-automation#45]
#### Is your Enhancement request related to a problem? Please describe

Would it be possible to implement a Scheduling type like "rerun as soon as it finished" (optionally with something like -delay 5 -seconds) and will the framework be able to handle that level of recurrence?

#### Describe how this would improve your Universal Automation Quality of Life

Please help us understand how this would improve your usage of Universal Automation and/or what new capabilities this enhancement would provide you with.

#### Describe alternatives you've considered

A clear and concise description of any alternative solutions or Enhancements you've considered.

#### Additional context

Add any other context or screenshots about the Enhancement request here.

**Comment by Windos** [comment]
Not sure if this is unique enough to split off into another topic, but how about "run as soon as that other script finishes"

This expands from continuations into dependencies

**Comment by adamdriscoll** [comment]
I think this is a different issue but a good one. I think we need to have a way to chain script execution easily. 

Would having events like "script to run after this script completes" or would pipelines where you select multiple scripts and chain them together make more sense? I don't want to go too crazy but some sort of pipeline concept might allow us to organize it better.
