### ISSUE TITLE
"ID" column in job history doesnt sort correctly

### ISSUE THREAD

**Issue by HansenRene** [ironmansoftware/universal-automation#46]
#### Describe the Issue

ID is the default sort column, but it doesn't sort right.

#### Screenshots

![image](https://user-images.githubusercontent.com/20628942/70693284-7412b080-1cbd-11ea-974f-5ff729142f72.png)

#### Script Sample

Attempt to attach sample code that will allow others to reproduce the issue. **NOTE**: Generally speaking this is the **MOST EFFECTIVE** way to have your issue resolved.

#### Version Information

- **Host Operating System**: 2019
- **Host PowerShell Version**:5.1
- **Universal Automation Version**: latest
- **Universal Dashboard Version**: 2.7
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)

**Comment by Chirishman** [comment]
Just found this myself. Looks like it's sorting as a string instead of an int.

Still happening on nightly build 2469

**Comment by Windos** [comment]
Yeah, looks like the ID is a string:

![image](https://user-images.githubusercontent.com/6955786/72227672-83f71a80-3604-11ea-8008-4a51bd0f609b.png)

I *think* this example is taken in build 2502.

**Comment by adamdriscoll** [comment]
This has been resolved in 0.0.3-beta3
