### ISSUE TITLE
Cannot Editor PowerShell Version in Dashboard

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-automation#50]
"PowerShell Versions" edits of entries don’t get saved. New entries are empty, all properties empty. (Not implemented ATM?) Empty object is created in database.

**Comment by Chirishman** [comment]
Well I don't know if this is still creating empty objects in the database but I currently cannot successfully edit the PowerShell version to be used for a script in the dashboard, either in the script settings or at runtime. Changing it via the powershell commands works fine.
