### ISSUE TITLE
Dashboard Fails if IE is not configured

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-automation#51]
"Invoke-WebRequest" at UniversalAutomation.psm1 line 70 fails on new systems, when Internet Explorer was never started (/fully configured).(WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand)

**Comment by TonyBunce** [comment]
If you don't use complex parsing of the request body add the "-UseBasicParsing" parameter to Invoke-WebRequest it won't use IE for the request
