### ISSUE TITLE
Error when committing without a message

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-automation#52]
Incomplete Git commits (no commit message) are accepted at the frontend, but then fail when getting commited by the UAServer. “Failed to commit. LibGit2Sharp.EmptyCommitException: No changes.”

**Comment by leeberg** [comment]
In the dashboard we do something like "No message specified" on Null - perhaps the cmdlet should do the same?

**Comment by adamdriscoll** [comment]
Yeah. I think thats a good idea. Check in both palces
