### ISSUE TITLE
Script Parameters tab

### ISSUE THREAD

**Issue by mattmcnabb** [ironmansoftware/universal-automation#54]
#### Describe the Issue

I'm getting an error on the Parameters tab for a script:

![image](https://user-images.githubusercontent.com/6998507/71057005-341e5400-2129-11ea-87fb-c4a8d3528c15.png)

I'm not sure what's causing this, but it happens on any script that has parameters defined.

#### Version Information

- **Host Operating System**: Windows 10
- **Host PowerShell Version**: PowerShell 6.2.3
- **Universal Automation Version**: build 2242
- **Universal Dashboard Version**: 2.7.0
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.) PowerShell

**Comment by leeberg** [comment]
Hey @mattmcnabb  could you please post your example script? I have tried a few example scripts with params and all seems OK. I am thinking there may be certain parameter type that is failing

**Comment by mattmcnabb** [comment]
yeah, it happens for this script:

```powershell
[CmdletBinding()]
param (
    [Parameter()]
    [string]
    $Parameter1
)

$Parameter1
```

**Comment by adamdriscoll** [comment]
Looking good now. 

![image](https://user-images.githubusercontent.com/1256531/71852527-2576ed00-3096-11ea-8e62-a1250fb3f500.png)
