### ISSUE TITLE
Sort "JOBS" view on script page in descending order

### ISSUE THREAD

**Issue by jantari** [ironmansoftware/universal-automation#55]
#### Is your Enhancement request related to a problem? Please describe

No, not related to a problem.

#### Describe the solution you'd like

When viewing "Past Jobs" on the main Dashboard, the jobs are sorted in descending order (latest job-id on top). This makes sense to me.

If I click on a script though, in the "Jobs" tab, the runs are sorted in ascending order by default.

I would like both views to be sorted in descending by default 👍 

#### Describe how this would improve your Universal Automation Quality of Life

The ascending order is less intuitive to me and the inconsistency also resulted in some miss-clicks already (instinctively clicking the top entry assuming it's the most recent run).

#### Describe alternatives you've considered

None

#### Additional context

UA Version: 2387

**Comment by adamdriscoll** [comment]
This was resolved in 0.0.3-beta3
