### ISSUE TITLE
Nulls being returned in Get-UAJobOutput

### ISSUE THREAD

**Issue by Chirishman** [ironmansoftware/universal-automation#57]
#### Describe the Issue

In certain scenarios, such as when a hashtable is written to the pipeline or the only output is a write-verbose a null information message record is output.

Multiple null records are returned around the hashtable, reflecting how console output would format it.

#### To Reproduce

1. Replace the `Write-Host` call in the provided getting started example with a hashtable literal
2. Run `Get-UAJobOutput` to retrieve the result

#### Expected behavior

Do not return null outputs or at least do not return multiple consecutive null outputs.

#### Script Sample

```PowerShell
Set-UAScript -Id 1 -content {start-sleep -Seconds 4; @{Hello='World'}}

Invoke-UAScript 1
```
#### Version Information

- Windows Server 2019:
- 5.1.17763.592:
- 2469:
- 2.8.1:
- PowerShell behind an NGNIX reverse proxy
- Am testing everything both through and around the reverse proxy

**Comment by adamdriscoll** [comment]
Resolved in tonight's build.
