### ISSUE TITLE
Alias Get-UAJobPipelineOutput to Receive-UAJob

### ISSUE THREAD

**Issue by Chirishman** [ironmansoftware/universal-automation#58]
#### Describe the solution you'd like

I would like a `Receive-UAJob` alias for `Get-UAJobPipelineOutput`.

#### Describe how this would improve your Universal Automation Quality of Life

I think this would help make the commands more discoverable and make the pattern of the commands more familiar to PowerShell users who have experience with the existing Jobs commands.

**Comment by adamdriscoll** [comment]
This is in tonight's build.
