### ISSUE TITLE
Flag to disable run on demand for a script

### ISSUE THREAD

**Issue by Chirishman** [ironmansoftware/universal-automation#59]
#### Describe the solution you'd like

I'd like a property to be added on script definitions to prevent adhoc running.

Something analogous to `New-ScheduledJobOption -DoNotAllowDemandStart`

#### Describe how this would improve your Universal Automation Quality of Life

Sometimes you have a job which you want to allow to run only at specific times, whether it performs maintenance actions which have the potential to interrupt service for normal users by rebooting something or takes an extremely long time to execute.

**Comment by adamdriscoll** [comment]
This has been implemented and will be in version 0.0.3-beta4
