### ISSUE TITLE
Null Job Output in Dashboard

### ISSUE THREAD

**Issue by Chirishman** [ironmansoftware/universal-automation#60]
#### Describe the Issue

Null job output in dashboard for Hello World example

#### To Reproduce

Run the code sample provided below and view the job output in the dashboard.

#### Expected behavior

Expected "Hello World" in the output

#### Script Sample

```PowerShell
$Script = New-UAScript -Name "My First Script" -ScriptBlock {Start-Sleep -Seconds 5; Write-Host "Hello World"}
Invoke-UAScript 1
```

#### Version Information

- Windows Server 2019:
- 5.1.17763.592:
- 2469:
- 2.8.1:
- PowerShell behind an NGNIX reverse proxy
- Am testing everything both through and around the reverse proxy

**Comment by Chirishman** [comment]
Possibly related to #3 ?

**Comment by adamdriscoll** [comment]
This is resolved in tonight's build.
