### ISSUE TITLE
Negative Time Saved

### ISSUE THREAD

**Issue by Chirishman** [ironmansoftware/universal-automation#61]
#### Describe the Issue

![image](https://user-images.githubusercontent.com/7658840/71744554-a5eae300-2e35-11ea-8f47-0f5ba3242a22.png)

<img src="https://user-images.githubusercontent.com/7658840/71744684-02e69900-2e36-11ea-8ed7-b9c1b26c0651.png" width="300">

#### To Reproduce

1. Follow the getting started example, let it run for a while.

#### Expected behavior

A positive number

#### Version Information

- Windows Server 2019:
- 5.1.17763.592:
- 2469:
- 2.8.1:
- PowerShell behind an NGNIX reverse proxy
- Am testing everything both through and around the reverse proxy

**Comment by adamdriscoll** [comment]
Fixed in tonight's build.
