### ISSUE TITLE
Tags meta data should be included in the git repo

### ISSUE THREAD

**Issue by Windos** [ironmansoftware/universal-automation#62]
I can see myself spending a fair amount of time setting up some tags with nice descriptions and colour coding.

Currently this info about the tags aren't included in the git repo, meaning if the database is wiped and UA is "restored" from git then there are two issues:

* Only tags that are referenced by scripts will be created, any that were created but not yet used will be lost.
* Only the name of the above tags are recreated, as that's all the info that's included in the script's meta data. This results in descriptions being blank and colours being black.

**Comment by adamdriscoll** [comment]
Tags are now stored in the git repo under '.ua/tags.psd1'
