### ISSUE TITLE
Pass parameter values to script using Invoke-UAScript

### ISSUE THREAD

**Issue by Windos** [ironmansoftware/universal-automation#63]
As a hypothetical: I'm wanting to create a logging script that I can invoke from other scripts.

The logging script takes two parameters, level (verbose, warning, error, etc) and message.

I can set this up and run the script, but if I try to invoke it via `Invoke-UAScript` I'm unable to provide parameter input, meaning it either has to rely on default values or would wait in a pending state for the required fields.

It'd be great if there was something like a Parameter parameter that accepted a hashtable, this would provide a similar experience to splatting.

**Comment by adamdriscoll** [comment]
This can be accomplished with dynamic parameters. So you can do someting like. 

```
Invoke-UAScript -Script $Script -Level 'Verbose' -Message 'Hello!'
```
