### ISSUE TITLE
Add Common Variables to All Scripts

### ISSUE THREAD

**Issue by leeberg** [ironmansoftware/universal-automation#64]
# Description
By exposing a few object variables to all scripts - we can assist in integrating with external systems/processes. 

* UAScirpt - Should be the script object
* UAJob - Should be the associated Job Object
* UASchedule - If the Job was scheduled - this will be the schedule object

**Note**: Post Public Beta :)

**Comment by adamdriscoll** [comment]
These variables have been added and will be in 0.0.3-beta4.
