### ISSUE TITLE
Ability to update and remove Secret Managers

### ISSUE THREAD

**Issue by Windos** [ironmansoftware/universal-automation#65]
Currently there is a two functions that reference secret managers:

* Get-UASecretManager
* New-UASecretManager

It should be possible to remove them (ADD: `Remove-UASecretManager`)

It is currently possible to add multiple Secret Managers with the same name (while fine... this could end up causing confusion, personally I expect them to be unique and get an error when running New- with a duplicate name)

![Duplicate Names, Secret Manager](https://user-images.githubusercontent.com/6955786/72311306-0f49dc00-36e9-11ea-8c18-0981755c6e82.png)

It should be possible to update an existing secret manager (ADD: `Set-UASecretManager`) to avoid the workflow of removing (once possible) and recreating with only a small change.

**Comment by leeberg** [comment]
Happy to report that this is now implemented - this should be going out with a new build that will be posted on 1/17/2020

New-Cmdlets 
  * ``Remove-UASecretManager``
  * ``Set-UASecretManager``

New UI Components:
![image](https://user-images.githubusercontent.com/274883/72585493-fb9ea100-38b3-11ea-9696-75439270f520.png)

![image](https://user-images.githubusercontent.com/274883/72585525-107b3480-38b4-11ea-85cf-58c4cc0284af.png)

![image](https://user-images.githubusercontent.com/274883/72585535-183ad900-38b4-11ea-8fac-ed87be936805.png)


We have some additional updates planned to make the "link" between a variable and a secret manager a bit more intuitive but this is still a decent step forward.
