### ISSUE TITLE
Editing a scheduled script via UD clears the schedule

### ISSUE THREAD

**Issue by Windos** [ironmansoftware/universal-automation#66]
#### Describe the Issue

When editing a script with an attached schedule via the UD script editor, the associated schedule is clear as a second git commit.

#### To Reproduce

- Open scheduled script in UD
- Edit the script using the integrated script editor
- Save changes
- See that there are no scheduled set for this script any more.

#### Expected behavior

... edit the script but leave the schedule.

#### Screenshots

Commit for editing the script:

![Script Edit Commit](https://user-images.githubusercontent.com/6955786/72311569-ff7ec780-36e9-11ea-9eb0-2ecc88d28fff.png)

Commit for removing the schedule:

![Remove Schedule Commit](https://user-images.githubusercontent.com/6955786/72311596-0f96a700-36ea-11ea-9fb2-b6f0589fd88b.png)

_Ignore the addition of the tag there, it is a separate bug._

#### Version Information

- **Host Operating System**: Windows Server 2019 (1809 - 17763.914)
- **Host PowerShell Version**: 5.1.17763.771
- **Universal Automation Version**: 1.0 (Build 2545)
- **Universal Dashboard Version**: 2.8.1
- **UD Hosting Method**: PowerShell

**Comment by leeberg** [comment]
Seems to be Cmdlet, Controller, GitSyncService issue... passing to @adamdriscoll

**Comment by adamdriscoll** [comment]
Fixed. Will be in 0.0.3-beta4.
