### ISSUE TITLE
Editing Tags via UD is not being written to meta files

### ISSUE THREAD

**Issue by Windos** [ironmansoftware/universal-automation#67]
#### Describe the Issue

When editing Tags on scripts via UD, the change shows in the UI but is not written to the *.meta.ps1 files (and therefore is not committed to Git)

If you edit something else the involves a scripts meta data, the tag information is included then.

_See #66 for an example of the inclusion of a tag being included in an unrelated git commit._

#### To Reproduce

- Open script in UD
- Add new Tag
- See that tag shows in the UA, both on the script page and the home page.
- See that this change has not been written to the meta.ps1 file, nor commited via git.

#### Expected behavior

This change should be written to the file and committed at the time of edit.

#### Screenshots

Tag in UD, not in Meta:

![Missing tag in Meta file](https://user-images.githubusercontent.com/6955786/72311933-45885b00-36eb-11ea-9acd-2f62ede70154.png)

Commit after changing description to force a Meta update:

![Forced Commit](https://user-images.githubusercontent.com/6955786/72311995-81bbbb80-36eb-11ea-9091-1c654b6125b3.png)

#### Version Information

- **Host Operating System**: Windows Server 2019 (1809 - 17763.914)
- **Host PowerShell Version**: 5.1.17763.771
- **Universal Automation Version**: 1.0 (Build 2545)
- **Universal Dashboard Version**: 2.8.1
- **UD Hosting Method**: PowerShell

**Comment by adamdriscoll** [comment]
Resolved in 0.0.3-beta6
