### ISSUE TITLE
Manual Time mislabeled as minutes

### ISSUE THREAD

**Issue by Windos** [ironmansoftware/universal-automation#68]
#### Describe the Issue

On a script page in UD, the script's Manual Time is mislabeled as minutes when it should be seconds.

This appears to just be a label issue, it doesn't affect the accumulated time saved.

#### To Reproduce

- Set a script to > 60 manual time
- Navigate to the script page in UD

#### Expected behavior

Seconds should be labeled seconds. (And I guess Hours should be labeled Hours if it scales up that high)

#### Screenshots

Scripts tab on home page showing correct label:

![correct label](https://user-images.githubusercontent.com/6955786/72312520-415d3d00-36ed-11ea-817c-8293db0e45d0.png)

Same script, on script page, showing 20 Minutes rather than  20 Seconds:

![incorrect label](https://user-images.githubusercontent.com/6955786/72312579-694ca080-36ed-11ea-9882-b67d1c0d94eb.png)

#### Version Information

- **Host Operating System**: Windows Server 2019 (1809 - 17763.914)
- **Host PowerShell Version**: 5.1.17763.771
- **Universal Automation Version**: 1.0 (Build 2545)
- **Universal Dashboard Version**: 2.8.1
- **UD Hosting Method**: PowerShell

**Comment by leeberg** [comment]
Nice Catch - will marge a fix tonight :)

**Comment by Windos** [comment]
If it helps similar string handling is already on the script tab of the
main page. I had a mix of seconds and minutes there

**Comment by leeberg** [comment]
Yep! Just merged the fix!
