### ISSUE TITLE
Sample script uses $PSScriptRoot, doesn't work interactively

### ISSUE THREAD

**Issue by Windos** [ironmansoftware/universal-automation#7]
#### Describe the Issue

When running the [sample script](https://docs.universalautomation.io/sample-script) interactively, the use of `$PSScriptRoot` results in errors if your working directory isn't the expected directory.

#### To Reproduce

1. Open PowerShell Console
2. Paste Sample Script
3. Notice errors as it executes

#### Expected behavior

Dynamically locate the module and reference the example script accordingly.

#### Screenshots

![image](https://user-images.githubusercontent.com/6955786/70202791-9b2e2700-177f-11ea-8adc-344def66a261.png)

#### Script Sample

Offending line is number 69:

```powershell
$Script = New-UAScript -Name "New User Onboarding Request" -ManualTime 28000 -ScriptBlock ([scriptblock]::Create((Get-Content "$PSScriptRoot\UniversalAutomation.Dashboard\examplescripts\onboarding.ps1"))) -Status "Draft"
```

Suggest change to:

```powershell
$Script = New-UAScript -Name "New User Onboarding Request" -ManualTime 28000 -ScriptBlock ([scriptblock]::Create((Get-Content "$((Get-Module UniversalAutomation.Dashboard -ListAvailable).ModuleBase)\examplescripts\onboarding.ps1"))) -Status "Draft"
```

#### Version Information

- **Host Operating System**: Windows 10 1909
- **Host PowerShell Version**: 5.1.18362.145
- **Universal Automation Version**: 1.0.0
- **Universal Dashboard Version**: 2.7.0
- **UD Hosting Method**: PowerShell

**Comment by adamdriscoll** [comment]
This shouldn't have been included with the sample script. It was part of one of our demo scripts and not a function of UA. I've fixed the sample script.
