### ISSUE TITLE
New Version Notification

### ISSUE THREAD

**Issue by leeberg** [ironmansoftware/universal-automation#70]
In our beta, we are going to have A LOT of new versions (daily or more) coming out responding to fixes/feedback from testers.

It would be nice to popup a notification in the product to indicate new version(s) are available.

* Toast or Banner at top of dashboard indicating a new version
* Easy (one click) to navigate to new version or specify update instructions
* Can disable notification (how dare you) on configs page

**Comment by adamdriscoll** [comment]
Implemented in 1.0 of PSU.
