### ISSUE TITLE
A $profile breaks different tabs in the dashboard of UA.

### ISSUE THREAD

**Issue by pminnebach** [ironmansoftware/universal-automation#73]
#### Describe the Issue

I have a powershell $profile that imports custom functions. This somehow breaks the following tabs in UA: Running Jobs, Past Jobs and Tags with the following error:

`Cannot bind parameter 'Script'. Cannot convert the "D:\OneDrive - xxx\Source\PowerShell Functions\Write-Header.ps1" value of type "System.IO.FileInfo" to type "UniversalAutomation.Script".`

The contents of my pscore 6 $profile is a dotsource of my regular windows powershell profile.

#### To Reproduce

Steps to reproduce the behavior: I removed my $profile

#### Expected behavior

It should show the correct information about the jobs etc w/o breaking over the presence of a $profile.

#### Screenshots

With a $profile:
![image](https://user-images.githubusercontent.com/4376572/72460124-8015f480-37cc-11ea-981b-b8b93e499bd1.png)

Without a $profile (or empty):
![image](https://user-images.githubusercontent.com/4376572/72459989-3decb300-37cc-11ea-8eff-d8874a827a21.png)

#### Script Sample

Attempt to attach sample code that will allow others to reproduce the issue. **NOTE**: Generally speaking this is the **MOST EFFECTIVE** way to have your issue resolved.

#### Version Information

- **Host Operating System**: Microsoft Windows Server 2019 Standard Build 17763
- **Host PowerShell Version**: PowerShell Core 6.2.3
- **Universal Automation Version**: 0.0.3
- **Universal Dashboard Version**: 2.8.1
- **UD Hosting Method**: PowerShell

**Comment by adamdriscoll** [comment]
Fixed in 0.0.3-beta3
