### ISSUE TITLE
GitSync Errors Cause Duplicate Records

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-automation#77]
When the Git Sync fails for whatever reason, it seems to attempt to resync over and over again which causes it to duplicate things like scripts and variables, etc.

**Comment by leeberg** [comment]
Note: Aggressively Test the GIT SYNC!

**Comment by adamdriscoll** [comment]
I think is has been resolved. I haven't seen it in the latest versions.
