### ISSUE TITLE
Identities are case-sensitive

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-automation#91]
![image](https://user-images.githubusercontent.com/1256531/73593957-a1fac100-44c6-11ea-9503-7be3eb1d0116.png)

**Comment by leeberg** [comment]
Implemented ToLower all over the Identity Controller...

Note, oddly  ``m => m.Name.Equals(name, System.StringComparison.OrdinalIgnoreCase)`` was not working at all. Replaced with simple ``ToLower()``
