### ISSUE TITLE
UA doesn't work in the ISE

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-automation#93]
See this: https://forums.universaldashboard.io/t/trying-to-get-ua-going/2151?u=adam

**Comment by Windos** [comment]
🤣 I always just assumed this was intended or un-avoidable. ISE was the first place I tried UA.

It looks like the -InProcess switch works, so the problem is likely around spawning the child process. This also causes an ISE instance to hang around after closing the ISE and locking the database.

**Comment by adamdriscoll** [comment]
Make me wonder how many other people did the exact same thing... figure it should be fixed.

**Comment by adamdriscoll** [comment]
This will be fixed in the next build.
